### ISSUE TITLE
PREPOSICIONES EJERCICIOS BY 23620031

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620031#1]
[proposiciones_matematicas_discretas_lopez_dominguez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620031/files/13111252/proposiciones_matematicas_discretas_lopez_dominguez.pdf)

**Comment by bibiana-m** [comment]
Portadas: 25%
Procedimientos: 25%
Figuras e ilustraciones: 25%
Resultado y conclusiones: 25%

Calificación: 100% / 10 * 20 = 20

Comentario: Bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
